### ISSUE TITLE
Admin Login Error

### ISSUE THREAD

**Issue by rennera** [RADB/Offord-EDI-2020#137]
![image](https://user-images.githubusercontent.com/3689865/149078562-2896dc3c-8594-4345-8470-9de50453a4f1.png)
Log details provided this information:
2022-01-12 01:14:55.480 -05:00 [ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDI.Web.Services.SharedService.InitializeUserSettings(String username) in C:\Users\andre\source\repos\Sources\Offord-EDI-2020\EDI\Web\Services\SharedService.cs:line 2072
   at EDI.Web.Layouts.MainLayout.OnInitializedAsync() in C:\Users\andre\source\repos\Sources\Offord-EDI-2020\EDI\Web\Layouts\MainLayout.razor:line 79

**Comment by rennera** [comment]
Source code shows province coming from identity database
`var province = _dbContext.Provinces.Where(p => p.Id == user1.ProvinceID).FirstOrDefault();`

Note the missing province and country
![image](https://user-images.githubusercontent.com/3689865/149078823-5847e324-5d51-49a1-b78e-760ddc3976ab.png)


Update the province and country
`  UPDATE [EDI.Identity].[dbo].[AspNetUsers]   SET countryID = 220, provinceID = 1045 WHERE username = 'andrew.renner@phri.ca'`

**Comment by rennera** [comment]
![image](https://user-images.githubusercontent.com/3689865/149079006-44dc544f-8a38-4c17-80c0-41e4dacfd5a3.png)
