### ISSUE TITLE
dbContext.Update disconnected data error on subsequent Saves

### ISSUE THREAD

**Issue by rennera** [RADB/Offord-EDI-2020#38]
When attaching disconnected data for updating you get an error when you attach disconnected data with the same ID a second time... ie Section A save - works - then Section B save - generates the following error

System.InvalidOperationException
  HResult=0x80131509
  Message=The instance of entity type 'Teacher' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Update[TEntity](TEntity entity)
   at EDI.Web.Shared.EDIHeader.<Save>d__8.MoveNext() in C:\Users\andre\source\repos\Sources\Offord-EDI-2020\EDI\Web\Shared\EDIHeader.razor:line 74

**Comment by rennera** [comment]
https://www.entityframeworktutorial.net/efcore/update-data-in-entity-framework-core.aspx
Speaks to the exact issue - but no resolution...
![image](https://user-images.githubusercontent.com/3689865/104198262-04a54e00-53f4-11eb-976c-95e46fbfeba3.png)

![image](https://user-images.githubusercontent.com/3689865/104198344-1edf2c00-53f4-11eb-984b-d5da6212d33d.png)

**Comment by rennera** [comment]
https://stackoverflow.com/questions/27423059/how-do-i-clear-tracked-entities-in-entity-framework

https://stackoverflow.com/questions/17771662/attach-and-entitystate-detached

**Comment by rennera** [comment]
Solved by creating a new instance every time you save:
```
private async void Save()
    {
        if (StateContainer.TeacherData != null)
        {
            var optionsBuilder = new DbContextOptionsBuilder<ServiceContext>();
            optionsBuilder.UseSqlServer(ConnectionStrings.ServiceConnection());
            using (ServiceContext servicecontext = new ServiceContext(optionsBuilder.Options))
            {
                servicecontext.Update(StateContainer.TeacherData);
                await servicecontext.SaveChangesAsync();

                StateContainer.SetTeacher(null);

                toastService.ShowSuccess("Data Saved Successfully!");

                StateHasChanged();
            }
        }
    }
```
