### ISSUE TITLE
Saving Section E causes Error 

### ISSUE THREAD

**Issue by rennera** [RADB/Offord-EDI-2020#39]
System.FormatException
  HResult=0x80131537
  Message=Input string was not in a correct format.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Byte.Parse(String s)
   at EDI.Web.Services.ReflectionService.SetFieldValue(Object obj, String fieldName, String value) in C:\Users\andre\source\repos\Sources\Offord-EDI-2020\EDI\Web\Services\ReflectionService.cs:line 35
   at EDI.Web.Services.ReflectionService.SetFieldValue(Teacher data, String entityName, String fieldName, String value) in C:\Users\andre\source\repos\Sources\Offord-EDI-2020\EDI\Web\Services\ReflectionService.cs:line 99
   at EDI.Web.Shared.Questionnaires.TextPart.<onChange>d__7.MoveNext() in C:\Users\andre\source\repos\Sources\Offord-EDI-2020\EDI\Web\Shared\Questionnaires\TextPart.razor:line 76

**Comment by rennera** [comment]
Investigation reveals an issue with the data model.  A text field is set as a tinyint.
![image](https://user-images.githubusercontent.com/3689865/104204267-13dbca00-53fb-11eb-8051-65fa7d2ef72d.png)

![image](https://user-images.githubusercontent.com/3689865/104204612-76cd6100-53fb-11eb-960e-fc6892d7d7eb.png)

**Comment by rennera** [comment]
Changed entity 
![image](https://user-images.githubusercontent.com/3689865/104205039-ed6a5e80-53fb-11eb-9e71-ceebfef0ae0d.png)

**Comment by rennera** [comment]
Added an exception trap and logging to the error:
![image](https://user-images.githubusercontent.com/3689865/104205958-fd367280-53fc-11eb-93de-ce25f441b6b3.png)

**Comment by rennera** [comment]
![image](https://user-images.githubusercontent.com/3689865/104206162-3969d300-53fd-11eb-86d5-f39f74ef1cbe.png)

Updated the model and it works as exected.
